name: Backend CI

on:
  push:
    paths:
      - "server/**"
    branches: ["main"]
  pull_request:
    paths:
      - "server/**"
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npx prisma generate
      - env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
        run: npx prisma migrate deploy
      - env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
        run: npm run test
