name: Frontend CI

on:
  push:
    paths:
      - "client/**"
    branches: ["main"]
  pull_request:
    paths:
      - "client/**"
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npm run lint
      - run: |
          npx playwright install
          npm run test:e2e
